export type CompanySymbol =
  | "AAPL"
  | "MSFT"
  | "NVDA"
  | "ADBE"
  | "INTC"
  | "AMD"
  | "CRM"
  | "NOW"
  | "CSCO"
  | "ORCL"
  | "PEP"
  | "KO"
  | "PG"
  | "MDLZ"
  | "CL"
  | "MO"
  | "KVUE"
  | "KMB"
  | "TSN"
  | "PPC"
  | "ADM"
  | "DE"
  | "BG"
  | "CTVA"
  | "NTR"
  | "CF"
  | "ANDE"
  | "CVGW"
  | "FDP"
  | "IPI"
  | "TSLA"
  | "F"
  | "GM"
  | "RIVN"
  | "LCID"
  | "NIO"
  | "TM"
  | "HMC"
  | "HYMTF"
  | "APTV"
  | "LMT"
  | "NOC"
  | "BA"
  | "RTX"
  | "RKLB"
  | "MAXR"
  | "IRDM"
  | "SPCE"
  | "ASTR"
  | "RDW"
  | "GOOGL"
  | "AMZN"
  | "META"
  | "IBM"
  | "PLTR"
  | "AI"
  | "SOUN"
  | "BBAI"
  | "JPM"
  | "BAC"
  | "C"
  | "WFC"
  | "GS"
  | "MS"
  | "USB"
  | "PNC"
  | "TFC"
  | "COF"
  | "UNH"
  | "PFE"
  | "JNJ"
  | "MRNA"
  | "MRK"
  | "ABBV"
  | "BMY"
  | "GILD"
  | "LLY"
  | "CVS"
  | "AMT"
  | "PLD"
  | "CCI"
  | "EQIX"
  | "PSA"
  | "SPG"
  | "WELL"
  | "O"
  | "AVB"
  | "DLR"
  | "XOM"
  | "CVX"
  | "COP"
  | "SLB"
  | "EOG"
  | "OXY"
  | "BKR"
  | "MRO"
  | "DVN"
  | "VLO"
  | "APH"
  | "ANET"
  | "DELL"
  | "CDNS"
  | "UPS"
  | "FDX"
  | "ODFL"
  | "DAL"
  | "UAL"
  | "LUV"
  | "EXPD"
  | "JBLU"
  | "ALK"
  | "AAL"
  | "NFLX"
  | "DIS"
  | "CMCSA"
  | "LYV"
  | "WBD"
  | "FWONA"
  | "FOX"
  | "PARA"
  | "ATVI"
  | "MGM";

export const companiesImages: Record<CompanySymbol, string> = {
  AAPL: "/assets/all_stocks/Apple.png",
  MSFT: "/assets/all_stocks/Microsoft.png",
  NVDA: "/assets/all_stocks/Nvidia.png",
  ADBE: "/assets/all_stocks/Adobe.png",
  INTC: "/assets/all_stocks/Intel.png",
  AMD: "/assets/all_stocks/AMD.png",
  CRM: "/assets/all_stocks/Salesforce.png",
  NOW: "/assets/all_stocks/ServiceNow.png",
  CSCO: "/assets/all_stocks/Cisco.png",
  ORCL: "/assets/all_stocks/oracle.png",
  PEP: "/assets/all_stocks/pepsico.png",
  KO: "/assets/all_stocks/Coca-Cola.png",
  PG: "/assets/all_stocks/procter_gamble.png",
  MDLZ: "/assets/all_stocks/Mondelez_international.png",
  CL: "/assets/all_stocks/colgate.png",
  MO: "/assets/all_stocks/Altria.png",
  KVUE: "/assets/all_stocks/Kenvue.png",
  KMB: "/assets/all_stocks/Kimberly-Clark.png",
  TSN: "/assets/all_stocks/Tyson_Foods.png",
  PPC: "/assets/all_stocks/pilgrims.png",
  ADM: "/assets/all_stocks/Archer-Daniels-Midland.png",
  DE: "/assets/all_stocks/Derre_Company.png",
  BG: "/assets/all_stocks/bunge-logo.png",
  CTVA: "/assets/all_stocks/Corteva.png",
  NTR: "/assets/all_stocks/Nutrien.png",
  CF: "/assets/all_stocks/CF_Industries.png",
  ANDE: "/assets/all_stocks/The_Andersons.png",
  CVGW: "/assets/all_stocks/Calavo_Growers.png",
  FDP: "/assets/all_stocks/Fresh_Del_Monte.png",
  IPI: "/assets/all_stocks/Intrepid_Potash.png",
  TSLA: "/assets/all_stocks/Tesla_logo.png",
  F: "/assets/all_stocks/Ford_Motor.png",
  GM: "/assets/all_stocks/General_Motors.png",
  RIVN: "/assets/all_stocks/rivian.png",
  LCID: "/assets/all_stocks/lucid-motors-logo.png",
  NIO: "/assets/all_stocks/nio.png",
  TM: "/assets/all_stocks/toyota.png",
  HMC: "/assets/all_stocks/honda-logo.png",
  HYMTF: "/assets/all_stocks/hyundai.png",
  APTV: "/assets/all_stocks/aptiv_logo.png",
  LMT: "/assets/all_stocks/LMT_BIG.png",
  NOC: "/assets/all_stocks/NOC_BIG.png",
  BA: "/assets/all_stocks/BA_BIG.png",
  RTX: "/assets/all_stocks/RTN_BIG.png",
  RKLB: "/assets/all_stocks/RKLB_BIG.png",
  MAXR: "/assets/all_stocks/MAXR_BIG.png",
  IRDM: "/assets/all_stocks/IRDM_BIG.png",
  SPCE: "/assets/all_stocks/SPCE_BIG.png",
  ASTR: "/assets/all_stocks/ASTR_BIG.png",
  RDW: "/assets/all_stocks/RDW_BIG.png",
  GOOGL: "/assets/all_stocks/Alphabet.png",
  AMZN: "/assets/all_stocks/Amazon.png",
  META: "/assets/all_stocks/Meta_Platforms.png",
  IBM: "/assets/all_stocks/IBM.png",
  PLTR: "/assets/all_stocks/Palantir.png",
  AI: "/assets/all_stocks/C3_ai.png",
  SOUN: "/assets/all_stocks/SoundHound_AI.png",
  BBAI: "/assets/all_stocks/BigBear_ai.png",
  JPM: "/assets/all_stocks/JPMorgan_Chase.png",
  BAC: "/assets/all_stocks/BAC_BIG.png",
  C: "/assets/all_stocks/Citi.png",
  WFC: "/assets/all_stocks/WFC.png",
  GS: "/assets/all_stocks/GS_BIG.png",
  MS: "/assets/all_stocks/MS_BIG.png",
  USB: "/assets/all_stocks/US_Bancorp.png",
  PNC: "/assets/all_stocks/PNC_BIG.png",
  TFC: "/assets/all_stocks/TFC_BIG.png",
  COF: "/assets/all_stocks/COF_BIG.png",
  UNH: "/assets/all_stocks/United_Health.png",
  PFE: "/assets/all_stocks/Pfizer.png",
  JNJ: "/assets/all_stocks/Johnson_Johnson.png",
  MRNA: "/assets/all_stocks/Moderna.png",
  MRK: "/assets/all_stocks/Merck_Co.png",
  ABBV: "/assets/all_stocks/AbbVie.png",
  BMY: "/assets/all_stocks/Bristol_Myers.png",
  GILD: "/assets/all_stocks/Gilead_Sciences.png",
  LLY: "/assets/all_stocks/Eli_Lilly.png",
  CVS: "/assets/all_stocks/CVS_Health.png",
  AMT: "/assets/all_stocks/AMT_BIG.png",
  PLD: "/assets/all_stocks/PLD_BIG.png",
  CCI: "/assets/all_stocks/CCI_BIG.png",
  EQIX: "/assets/all_stocks/EQIX_BIG.png",
  PSA: "/assets/all_stocks/PSA.png",
  SPG: "/assets/all_stocks/SPG_BIG.png",
  WELL: "/assets/all_stocks/WELL.png",
  O: "/assets/all_stocks/O_BIG.png",
  AVB: "/assets/all_stocks/AVB.png",
  DLR: "/assets/all_stocks/DLR_BIG.png",
  XOM: "/assets/all_stocks/ExxonMobil.png",
  CVX: "/assets/all_stocks/Chevron.png",
  COP: "/assets/all_stocks/Conoco_Phillips.png",
  SLB: "/assets/all_stocks/Schlumberger.png",
  EOG: "/assets/all_stocks/EOG_Resources.png",
  OXY: "/aassets/all_stocks/Occidental_Petroleum.png",
  BKR: "/assets/all_stocks/Baker_Hughes.png",
  MRO: "/assets/all_stocks/Marathon_Oil.png",
  DVN: "/assets/all_stocks/Devon_Energy.png",
  VLO: "/assets/all_stocks/Valero_Energy.png",
  APH: "/assets/all_stocks/APH_BIG.png",
  ANET: "/assets/all_stocks/ANET_BIG.png",
  DELL: "/assets/all_stocks/DELL_BIG.png",
  CDNS: "/assets/all_stocks/CDNS_BIG.png",
  UPS: "/assets/all_stocks/United_Parcel_Service.png",
  FDX: "/assets/all_stocks/FedEx_Corporation.png",
  ODFL: "/assets/all_stocks/Old_Dominion_Freight_Line.png",
  DAL: "/assets/all_stocks/Delta_Air_Lines.png",
  UAL: "/assets/all_stocks/United_Airlines_Holdings.png",
  LUV: "/assets/all_stocks/Southwest_Airlines.png",
  EXPD: "/assets/all_stocks/American_Airlines_Group.png",
  JBLU: "/assets/all_stocks/JetBlue_Airways.png",
  ALK: "/assets/all_stocks/Alaska_Air_Group.png",
  AAL: "/assets/all_stocks/Expeditors.png",
  NFLX: "/assets/all_stocks/NFLX_BIG.png",
  DIS: "/assets/all_stocks/DIS_BIG.png",
  CMCSA: "/assets/all_stocks/comcast.png",
  LYV: "/assets/all_stocks/LiveNationLogo.png",
  WBD: "/assets/all_stocks/Warner_Bros.png",
  FWONA: "/assets/all_stocks/FWONK_BIG.png",
  FOX: "/assets/all_stocks/fox_corp.png",
  PARA: "/assets/all_stocks/PARA_BIG.png",
  ATVI: "/assets/all_stocks/ATVI_BIG.png",
  MGM: "/assets/all_stocks/MGM_BIG.png",
};
