export interface CarouselCardData {
  id: number;
  title: string;
  icon: string;
  bgColor: string;
  textColor: string;
  tintColorClass: string;
  growth: number;
}

export const carouselData: CarouselCardData[] = [
  {
    id: 1,
    title: "Amazon",
    icon: "/assets/stocks/1.png",
    bgColor: "bg-gradient-to-br from-yellow-200 to-yellow-300",
    textColor: "text-black",
    tintColorClass: "from-yellow-400",
    growth: 119.43,
  },
  {
    id: 2,
    title: "Walmart",
    icon: "/assets/stocks/2.png",
    bgColor: "bg-gradient-to-br from-indigo-200 to-indigo-300",
    textColor: "text-black",
    tintColorClass: "from-indigo-400",
    growth: 141.27,
  },
  {
    id: 3,
    title: "Tesla",
    icon: "/assets/stocks/3.png",
    bgColor: "bg-gradient-to-br from-rose-200 to-rose-300",
    textColor: "text-black",
    tintColorClass: "from-rose-400",
    growth: 1453.57,
  },
  {
    id: 4,
    title: "Hp",
    icon: "/assets/stocks/4.png",
    bgColor: "bg-gradient-to-br from-green-200 to-green-300",
    textColor: "text-black",
    tintColorClass: "from-green-400",
    growth: 163.5,
  },
  {
    id: 5,
    title: "Intel",
    icon: "/assets/stocks/5.png",
    bgColor: "bg-gradient-to-br from-sky-200 to-sky-300",
    textColor: "text-black",
    tintColorClass: "from-sky-400",
    growth: 56,
  },
  {
    id: 6,
    title: "JP Morgan",
    icon: "/assets/stocks/6.png",
    bgColor: "bg-gradient-to-br from-purple-200 to-purple-300",
    textColor: "text-black",
    tintColorClass: "from-purple-400",
    growth: 12,
  },
  {
    id: 7,
    title: "Microsoft",
    icon: "/assets/stocks/7.png",
    bgColor: "bg-gradient-to-br from-pink-200 to-pink-300",
    textColor: "text-black",
    tintColorClass: "from-pink-400",
    growth: 68,
  },
  {
    id: 8,
    title: "Nvidia",
    icon: "/assets/stocks/8.png",
    bgColor: "bg-gradient-to-br from-red-200 to-red-300",
    textColor: "text-black",
    tintColorClass: "from-red-400",
    growth: 37,
  },
  {
    id: 9,
    title: "Chevron",
    icon: "/assets/stocks/9.png",
    bgColor: "bg-gradient-to-br from-teal-200 to-teal-300",
    textColor: "text-black",
    tintColorClass: "from-teal-400",
    growth: 78,
  },
  {
    id: 10,
    title: "Visa",
    icon: "/assets/stocks/10.png",
    bgColor: "bg-gradient-to-br from-lime-200 to-lime-300",
    textColor: "text-black",
    tintColorClass: "from-lime-400",
    growth: 45,
  },
  {
    id: 11,
    title: "Apple",
    icon: "/assets/stocks/11.png",
    bgColor: "bg-gradient-to-br from-blue-200 to-blue-300",
    textColor: "text-black",
    tintColorClass: "from-blue-400",
    growth: 67,
  },
  {
    id: 12,
    title: "Coca Cola",
    icon: "/assets/stocks/12.png",
    bgColor: "bg-gradient-to-br from-orange-200 to-orange-300",
    textColor: "text-black",
    tintColorClass: "from-orange-400",
    growth: 90,
  },
];

export interface CarouselStyleData {
  id: number;
  bgColor: string;
  textColor: string;
  tintColorClass: string;
}

export const carouselStyleData: CarouselStyleData[] = [
  {
    id: 1,
    bgColor: "bg-gradient-to-br from-yellow-200 to-yellow-300",
    textColor: "text-black",
    tintColorClass: "from-yellow-400",
  },
  {
    id: 2,
    bgColor: "bg-gradient-to-br from-indigo-200 to-indigo-300",
    textColor: "text-black",
    tintColorClass: "from-indigo-400",
  },
  {
    id: 3,
    bgColor: "bg-gradient-to-br from-rose-200 to-rose-300",
    textColor: "text-black",
    tintColorClass: "from-rose-400",
  },
  {
    id: 4,
    bgColor: "bg-gradient-to-br from-green-200 to-green-300",
    textColor: "text-black",
    tintColorClass: "from-green-400",
  },
  {
    id: 5,
    bgColor: "bg-gradient-to-br from-sky-200 to-sky-300",
    textColor: "text-black",
    tintColorClass: "from-sky-400",
  },
  {
    id: 6,
    bgColor: "bg-gradient-to-br from-purple-200 to-purple-300",
    textColor: "text-black",
    tintColorClass: "from-purple-400",
  },
  {
    id: 7,
    bgColor: "bg-gradient-to-br from-pink-200 to-pink-300",
    textColor: "text-black",
    tintColorClass: "from-pink-400",
  },
  {
    id: 8,
    bgColor: "bg-gradient-to-br from-red-200 to-red-300",
    textColor: "text-black",
    tintColorClass: "from-red-400",
  },
  {
    id: 9,
    bgColor: "bg-gradient-to-br from-teal-200 to-teal-300",
    textColor: "text-black",
    tintColorClass: "from-teal-400",
  },
  {
    id: 10,
    bgColor: "bg-gradient-to-br from-lime-200 to-lime-300",
    textColor: "text-black",
    tintColorClass: "from-lime-400",
  },
  {
    id: 11,
    bgColor: "bg-gradient-to-br from-blue-200 to-blue-300",
    textColor: "text-black",
    tintColorClass: "from-blue-400",
  },
  {
    id: 12,
    bgColor: "bg-gradient-to-br from-orange-200 to-orange-300",
    textColor: "text-black",
    tintColorClass: "from-orange-400",
  },
];

export type Company = {
  symbol: string;
  name: string;
  priceUSD?: number;
  openingPrice?: number;
  closingPrice?: number;
  highestPrice?: string | number;
  lowestPrice?: string | number;
  growth: string;
  marketCap: string;
  topProducts: string[];
};

export type CompanyDataset = Record<string, Company[]>;

export const companyData = {
  it: [
    {
      symbol: "AAPL",
      name: "Apple",
      priceUSD: 213.07,
      openingPrice: 91.28,
      closingPrice: 200.3,
      highestPrice: "",
      lowestPrice: "",
      growth: "119.43%",
      marketCap: "3.3T",
      topProducts: [
        "iPhone",
        "MacBook",
        "iPad",
        "Apple Watch",
        "AirPods",
        "iOS",
        "macOS",
        "Apple Music",
        "Apple TV+",
        "iCloud",
      ],
    },
    {
      symbol: "MSFT",
      name: "Microsoft",
      priceUSD: 443.56,
      openingPrice: 203.14,
      closingPrice: 490.11,
      highestPrice: "",
      lowestPrice: "",
      growth: "141.27%",
      marketCap: "3.6T",
      topProducts: [
        "Windows OS",
        "Microsoft Office",
        "Azure",
        "Teams",
        "Xbox",
        "Outlook",
        "Power BI",
        "Visual Studio",
        "OneDrive",
        "LinkedIn",
      ],
    },
    {
      symbol: "NVDA",
      name: "Nvidia",
      priceUSD: 130.98,
      openingPrice: 9.52,
      closingPrice: 147.9,
      highestPrice: "",
      lowestPrice: "",
      growth: "1453.57%",
      marketCap: "3.2T",
      topProducts: [
        "GeForce GPUs",
        "RTX Series",
        "Quadro",
        "Tesla GPUs",
        "DGX Systems",
        "CUDA",
        "Omniverse",
        "Jetson",
        "NVIDIA AI Enterprise",
        "NVLink",
      ],
    },
    {
      symbol: "ADBE",
      name: "Adobe",
      priceUSD: 466.12,
      openingPrice: 434.8,
      closingPrice: 382.34,
      highestPrice: "",
      lowestPrice: "",
      growth: "-12.07%",
      marketCap: "210B",
      topProducts: [
        "Photoshop",
        "Illustrator",
        "Premiere Pro",
        "After Effects",
        "Lightroom",
        "Adobe XD",
        "InDesign",
        "Acrobat Reader",
        "Adobe Express",
        "Creative Cloud",
      ],
    },
    {
      symbol: "INTC",
      name: "Intel",
      priceUSD: 30.56,
      openingPrice: 59.91,
      closingPrice: 22.55,
      highestPrice: "",
      lowestPrice: "",
      growth: "-62.36%",
      marketCap: "130B",
      topProducts: [
        "Core Processors",
        "Xeon Processors",
        "Arc GPUs",
        "Intel NUC",
        "Optane Memory",
        "Intel Evo",
        "Intel Mobileye",
        "FPGAs (Altera)",
        "Intel Foundry",
        "Thunderbolt",
      ],
    },
    {
      symbol: "AMD",
      name: "AMD",
      priceUSD: 151.86,
      openingPrice: 52.63,
      closingPrice: 138.43,
      highestPrice: "",
      lowestPrice: "",
      growth: "163.02%",
      marketCap: "245B",
      topProducts: [
        "Ryzen CPUs",
        "Radeon GPUs",
        "EPYC Server CPUs",
        "Threadripper",
        "Instinct Accelerators",
        "Adrenalin Software",
        "Xilinx FPGAs",
        "PRO Series CPUs",
        "FreeSync",
        "AMD Software Suite",
      ],
    },
    {
      symbol: "CRM",
      name: "Salesforce",
      priceUSD: 247.17,
      openingPrice: 188.1,
      closingPrice: 271.17,
      highestPrice: "",
      lowestPrice: "",
      growth: "44.16%",
      marketCap: "240B",
      topProducts: [
        "Sales Cloud",
        "Service Cloud",
        "Marketing Cloud",
        "Commerce Cloud",
        "Experience Cloud",
        "Tableau",
        "MuleSoft",
        "Slack",
        "Einstein AI",
        "Salesforce Platform",
      ],
    },
    {
      symbol: "NOW",
      name: "ServiceNow",
      priceUSD: 735.67,
      openingPrice: 405.38,
      closingPrice: 996.32,
      highestPrice: "",
      lowestPrice: "",
      growth: "145.77%",
      marketCap: "150B",
      topProducts: [
        "ITSM",
        "ITOM",
        "ITBM",
        "HR Service Delivery",
        "Security Operations",
        "Governance, Risk, and Compliance",
        "Customer Service Management",
        "Now Platform",
        "App Engine",
        "Industry-specific solutions",
      ],
    },
    {
      symbol: "CSCO",
      name: "Cisco",
      priceUSD: 45.28,
      openingPrice: 46.54,
      closingPrice: 67.89,
      highestPrice: "",
      lowestPrice: "",
      growth: "45.87%",
      marketCap: "183B",
      topProducts: [
        "Catalyst Switches",
        "Cisco Meraki",
        "Webex",
        "Cisco DNA",
        "UCS Servers",
        "Firepower Security",
        "Cisco ACI",
        "ThousandEyes",
        "Cisco SecureX",
        "Security Cloud",
      ],
    },
    {
      symbol: "ORCL",
      name: "Oracle",
      priceUSD: 139.98,
      openingPrice: 54.4,
      closingPrice: 215.27,
      highestPrice: "",
      lowestPrice: "",
      growth: "295.72%",
      marketCap: "383B",
      topProducts: [
        "Oracle Database",
        "Oracle Cloud Infrastructure",
        "Oracle Fusion ERP",
        "MySQL",
        "Java",
        "PeopleSoft",
        "NetSuite",
        "Oracle Analytics",
        "Oracle Middleware",
        "OCI AI Services",
      ],
    },
  ],
  fmcg: [
    {
      symbol: "PEP",
      name: "PepsiCo",
      priceUSD: 130.85,
      openingPrice: 132.5,
      closingPrice: 131.5,
      highestPrice: "",
      lowestPrice: "",
      growth: "-0.75%",
      marketCap: "274B",
      topProducts: [
        "Pepsi",
        "Mountain Dew",
        "Gatorade",
        "Lay’s",
        "Doritos",
        "Quaker Oats",
        "Tropicana",
        "7UP",
        "Aquafina",
        "Cheetos",
      ],
    },
    {
      symbol: "KO",
      name: "Coca‑Cola",
      priceUSD: 71.02,
      openingPrice: 44.93,
      closingPrice: 70.21,
      highestPrice: "",
      lowestPrice: "",
      growth: "56.27%",
      marketCap: "304B",
      topProducts: [
        "Coca-Cola (Classic)",
        "Sprite",
        "Fanta",
        "Minute Maid",
        "Smartwater",
        "Dasani",
        "Powerade",
        "Coca-Cola Zero Sugar",
        "Simply",
        "Gold Peak Tea",
      ],
    },
    {
      symbol: "PG",
      name: "Procter & Gamble",
      priceUSD: 160.28,
      openingPrice: 119.65,
      closingPrice: 160.36,
      highestPrice: "",
      lowestPrice: "",
      growth: "34.02%",
      marketCap: "363B",
      topProducts: [
        "Pampers",
        "Tide",
        "Ariel",
        "Gillette",
        "Head & Shoulders",
        "Downy",
        "Oral-B",
        "Pantene",
        "Vicks",
        "Old Spice",
      ],
    },
    {
      symbol: "MDLZ",
      name: "Mondelez",
      priceUSD: 66.93,
      openingPrice: 51.06,
      closingPrice: 68.43,
      highestPrice: "",
      lowestPrice: "",
      growth: "34.02%",
      marketCap: "96B",
      topProducts: [
        "Oreo",
        "LU",
        "Cadbury",
        "Milka",
        "Toblerone",
        "Trident",
        "Halls",
        "BelVita",
        "Chips Ahoy!",
        "Ritz",
      ],
    },
    {
      symbol: "CL",
      name: "Colgate‑Palmolive",
      priceUSD: 90.26,
      openingPrice: 73.26,
      closingPrice: 88.18,
      highestPrice: "",
      lowestPrice: "",
      growth: "20.37%",
      marketCap: "77B",
      topProducts: [
        "Colgate",
        "Palmolive",
        "Speed Stick",
        "Softsoap",
        "Irish Spring",
        "Suavitel",
        "Tom’s of Maine",
        "Sanex",
        "Protex",
        "Hill's Pet Nutrition",
      ],
    },
    {
      symbol: "MO",
      name: "Altria",
      priceUSD: 59.81,
      openingPrice: 39.43,
      closingPrice: 59.91,
      highestPrice: "",
      lowestPrice: "",
      growth: "51.94%",
      marketCap: "87B",
      topProducts: [
        "Marlboro",
        "Black & Mild",
        "Skoal",
        "Copenhagen",
        "Basic",
        "Parliament",
        "Virginia Slims",
        "Red Seal",
        "MarkTen",
        "Helix Innovations",
      ],
    },
    {
      symbol: "KVUE",
      name: "Kenvue",
      priceUSD: 21.45,
      openingPrice: 25.53,
      closingPrice: 21.19,
      highestPrice: "",
      lowestPrice: "",
      growth: "-17.00%",
      marketCap: "24B",
      topProducts: [
        "Tylenol",
        "Nicorette",
        "Listerine",
        "Neutrogena",
        "Aveeno",
        "Johnson’s Baby",
        "Motrin",
        "Zarbee’s",
        "Band-Aid",
        "Benadryl",
      ],
    },
    {
      symbol: "KMB",
      name: "Kimberly‑Clark",
      priceUSD: 130.84,
      openingPrice: 141.16,
      closingPrice: 129.95,
      highestPrice: "",
      lowestPrice: "",
      growth: "-7.94%",
      marketCap: "49B",
      topProducts: [
        "Huggies",
        "GoodNites",
        "Kleenex",
        "Cottonelle",
        "Scott",
        "Pull-Ups",
        "Poise",
        "Depend",
        "WypAll",
        "Andrex",
      ],
    },
    {
      symbol: "TSN",
      name: "Tyson Foods",
      priceUSD: 54.81,
      openingPrice: 59.68,
      closingPrice: 55.51,
      highestPrice: "",
      lowestPrice: "",
      growth: "-6.99%",
      marketCap: "25B",
      topProducts: [
        "Tyson",
        "Jimmy Dean",
        "Hillshire Farm",
        "Ball Park",
        "Wright Brand",
        "Aidells",
        "Stewart Sandwiches",
        "State Fair",
        "Any’tizers",
        "NatureRaised Farms",
      ],
    },
    {
      symbol: "PPC",
      name: "Pilgrim’s Pride",
      priceUSD: 46.14,
      openingPrice: 38.61,
      closingPrice: 46.62,
      highestPrice: "",
      lowestPrice: "",
      growth: "20.75%",
      marketCap: "4B",
      topProducts: [
        "Pilgrim’s",
        "Gold’n Plump",
        "Just Bare",
        "Pierce Chicken",
        "Del Dia",
        "County Pride",
        "Wing Dings",
        "To-Ricos",
        "Savoro",
        "Chicken Plus",
      ],
    },
  ],
  agriculture: [
    {
      symbol: "ADM",
      name: "Archer-Daniels-Midland",
      priceUSD: 60.21,
      openingPrice: 40.1,
      closingPrice: 52.93,
      highestPrice: "",
      lowestPrice: "",
      growth: "32.00%",
      marketCap: "32B",
      topProducts: [
        "Corn processing",
        "Soy protein",
        "Flavors & extracts",
        "Animal nutrition",
        "Ethanol",
        "Vegetable oils",
        "Wheat milling",
        "Bio-based industrial products",
        "Cocoa processing",
        "Emulsifiers & stabilizers",
      ],
    },
    {
      symbol: "DE",
      name: "Deere & Company",
      priceUSD: 378.56,
      openingPrice: 159.65,
      closingPrice: 514.1,
      highestPrice: "",
      lowestPrice: "",
      growth: "222.02%",
      marketCap: "109B",
      topProducts: [
        "Tractors",
        "Harvesters",
        "Planters",
        "Sprayers",
        "Construction equipment",
        "Forestry equipment",
        "Aftermarket parts",
        "Precision ag software",
        "Autonomous tractors",
        "John Deere Financial Services",
      ],
    },
    {
      symbol: "BG",
      name: "Bunge",
      priceUSD: 105.18,
      openingPrice: 41.1,
      closingPrice: 83.59,
      highestPrice: "",
      lowestPrice: "",
      growth: "103.38%",
      marketCap: "15B",
      topProducts: [
        "Soybean oil",
        "Grain trading",
        "Rapeseed oil",
        "Sunflower oil",
        "Margarine",
        "Baking ingredients",
        "Animal feed",
        "Biofuels",
        "Refined sugar",
        "Plant-based proteins",
      ],
    },
    {
      symbol: "CTVA",
      name: "Corteva",
      priceUSD: 55.47,
      openingPrice: 26.95,
      closingPrice: 73.29,
      highestPrice: "",
      lowestPrice: "",
      growth: "171.95%",
      marketCap: "39B",
      topProducts: [
        "Corn seeds",
        "Soybean seeds",
        "Fungicides",
        "Herbicides",
        "Insecticides",
        "Seed coatings",
        "Biologicals",
        "Nitrogen stabilizers",
        "Digital ag tools",
        "Crop protection platforms",
      ],
    },
    {
      symbol: "NTR",
      name: "Nutrien",
      priceUSD: 54.23,
      openingPrice: 32.25,
      closingPrice: 59.42,
      highestPrice: "",
      lowestPrice: "",
      growth: "84.25%",
      marketCap: "28B",
      topProducts: [
        "Potash",
        "Nitrogen fertilizers",
        "Phosphate products",
        "Ammonium nitrate",
        "Urea",
        "Crop advisors",
        "Ag retail centers",
        "Soil health tools",
        "Digital crop services",
        "Specialty ag inputs",
      ],
    },
    {
      symbol: "CF",
      name: "CF Industries",
      priceUSD: 79.6,
      openingPrice: 28.23,
      closingPrice: 94.68,
      highestPrice: "",
      lowestPrice: "",
      growth: "235.39%",
      marketCap: "15B",
      topProducts: [
        "Ammonia",
        "UAN (urea ammonium nitrate)",
        "Urea",
        "AN (ammonium nitrate)",
        "Nitrogen fertilizers",
        "Green ammonia",
        "DEF (diesel exhaust fluid)",
        "Industrial nitrogen",
        "Nutrient delivery systems",
        "Low-carbon fertilizer",
      ],
    },
    {
      symbol: "ANDE",
      name: "The Andersons",
      priceUSD: 53.72,
      openingPrice: 13.76,
      closingPrice: 36.79,
      highestPrice: "",
      lowestPrice: "",
      growth: "167.37%",
      marketCap: "2B",
      topProducts: [
        "Grain trading",
        "Fertilizer distribution",
        "Ethanol",
        "Rail leasing",
        "Logistics",
        "Plant nutrients",
        "Crop inputs",
        "Food ingredients",
        "Specialty grains",
        "Agronomy services",
      ],
    },
    {
      symbol: "CVGW",
      name: "Calavo Growers",
      priceUSD: 28.91,
      openingPrice: 62.65,
      closingPrice: 27,
      highestPrice: "",
      lowestPrice: "",
      growth: "-56.90%",
      marketCap: "0.5B",
      topProducts: [
        "Avocados",
        "Guacamole",
        "Fresh-cut fruit",
        "Salsas",
        "Tomatoes",
        "Papayas",
        "Mangoes",
        "Tropical produce",
        "Foodservice avocado products",
        "Branded deli products",
      ],
    },
    {
      symbol: "FDP",
      name: "Fresh Del Monte",
      priceUSD: 23.15,
      openingPrice: 24.68,
      closingPrice: 32.72,
      highestPrice: "",
      lowestPrice: "",
      growth: "32.58%",
      marketCap: "1B",
      topProducts: [
        "Bananas",
        "Pineapples",
        "Avocados",
        "Melons",
        "Mangos",
        "Fresh-cut fruits",
        "Fruit juice",
        "Vegetables",
        "Plant-based products",
        "Snack fruit packs",
      ],
    },
    {
      symbol: "IPI",
      name: "Intrepid Potash",
      priceUSD: 19.24,
      openingPrice: 9.7,
      closingPrice: 35.74,
      highestPrice: "",
      lowestPrice: "",
      growth: "268.45%",
      marketCap: "0.3B",
      topProducts: [
        "Potash (MOP)",
        "Langbeinite (Trio)",
        "Salt",
        "Brine water",
        "Water services",
        "Soil enhancers",
        "Magnesium products",
        "Deicing salt",
        "Irrigation-grade minerals",
        "Agricultural minerals",
      ],
    },
  ],
  automotive: [
    {
      symbol: "TSLA",
      name: "Tesla",
      priceUSD: 180.04,
      openingPrice: 72.47,
      closingPrice: 340.47,
      highestPrice: "",
      lowestPrice: "",
      growth: "369.81%",
      marketCap: "570B",
      topProducts: [
        "Model 3",
        "Model Y",
        "Model S",
        "Model X",
        "Cybertruck",
        "Roadster",
        "Semi",
        "Powerwall",
        "Megapack",
        "Solar Roof",
      ],
    },
    {
      symbol: "F",
      name: "Ford",
      priceUSD: 12.11,
      openingPrice: 6.1,
      closingPrice: 10.73,
      highestPrice: "",
      lowestPrice: "",
      growth: "75.90%",
      marketCap: "48B",
      topProducts: [
        "F-150",
        "Mustang Mach-E",
        "Explorer",
        "Escape",
        "Bronco",
        "Ranger",
        "Transit",
        "Edge",
        "Maverick",
        "E-Transit",
      ],
    },
    {
      symbol: "GM",
      name: "General Motors",
      priceUSD: 46.83,
      openingPrice: 25.3,
      closingPrice: 49,
      highestPrice: "",
      lowestPrice: "",
      growth: "93.68%",
      marketCap: "53B",
      topProducts: [
        "Chevrolet Silverado",
        "Chevrolet Equinox",
        "Chevrolet Bolt EV",
        "GMC Sierra",
        "Cadillac Escalade",
        "Cadillac LYRIQ",
        "GMC Hummer EV",
        "Buick Enclave",
        "Cruise (Autonomous)",
        "OnStar",
      ],
    },
    {
      symbol: "RIVN",
      name: "Rivian",
      priceUSD: 10.35,
      openingPrice: 106.75,
      closingPrice: 13.81,
      highestPrice: "",
      lowestPrice: "",
      growth: "-87.06%",
      marketCap: "10B",
      topProducts: [
        "R1T",
        "R1S",
        "Electric Delivery Van (EDV)",
        "Fleet Management Software",
        "Rivian Adventure Network",
        "Custom Interiors",
        "Quad-Motor AWD",
        "Removable Roof Options",
        "Gear Tunnel Accessories",
        "Rivian App",
      ],
    },
    {
      symbol: "LCID",
      name: "Lucid Motors",
      priceUSD: 2.98,
      openingPrice: 10.25,
      closingPrice: 2.17,
      highestPrice: "",
      lowestPrice: "",
      growth: "-78.83%",
      marketCap: "7B",
      topProducts: [
        "Lucid Air Pure",
        "Lucid Air Touring",
        "Lucid Air Grand Touring",
        "Lucid Air Sapphire",
        "Lucid Gravity (SUV)",
        "DreamDrive Pro",
        "Lucid Studio",
        "Wonderbox Charging",
        "Glass Cockpit Interface",
        "Over-the-Air Updates",
      ],
    },
    {
      symbol: "NIO",
      name: "NIO",
      priceUSD: 4.22,
      openingPrice: 7.79,
      closingPrice: 3.5,
      highestPrice: "",
      lowestPrice: "",
      growth: "-55.07%",
      marketCap: "9B",
      topProducts: [
        "ES6",
        "ES8",
        "EC6",
        "ET7",
        "ET5",
        "Battery Swap Stations",
        "NOMI AI Assistant",
        "NIO Pilot",
        "BaaS (Battery-as-a-Service)",
        "Banyan Operating System",
      ],
    },
    {
      symbol: "TM",
      name: "Toyota",
      priceUSD: 203,
      openingPrice: 124.76,
      closingPrice: 171.58,
      highestPrice: "",
      lowestPrice: "",
      growth: "37.53%",
      marketCap: "275B",
      topProducts: [
        "Corolla",
        "Camry",
        "RAV4",
        "Highlander",
        "Land Cruiser",
        "Tacoma",
        "Tundra",
        "Prius",
        "Mirai (Hydrogen)",
        "Innova",
      ],
    },
    {
      symbol: "HMC",
      name: "Honda",
      priceUSD: 33.67,
      openingPrice: 25.18,
      closingPrice: 28.88,
      highestPrice: "",
      lowestPrice: "",
      growth: "14.69%",
      marketCap: "57B",
      topProducts: [
        "Civic",
        "Accord",
        "CR-V",
        "Pilot",
        "Fit",
        "Ridgeline",
        "Odyssey",
        "Honda e",
        "Clarity",
        "HondaJet",
      ],
    },
    {
      symbol: "HYMTF",
      name: "Hyundai",
      priceUSD: 49.8,
      openingPrice: 25.25,
      closingPrice: 56.38,
      highestPrice: "",
      lowestPrice: "",
      growth: "123.29%",
      marketCap: "32B",
      topProducts: [
        "Creta",
        "Tucson",
        "Santa Fe",
        "Venue",
        "Verna",
        "Elantra",
        "Palisade",
        "Kona Electric",
        "IONIQ 5",
        "Staria",
      ],
    },
    {
      symbol: "APTV",
      name: "Aptiv",
      priceUSD: 75.24,
      openingPrice: 77.91,
      closingPrice: 68.45,
      highestPrice: "",
      lowestPrice: "",
      growth: "-12.14%",
      marketCap: "20B",
      topProducts: [
        "Active Safety Systems",
        "ADAS Sensors",
        "High-Voltage Cabling",
        "Signal & Power Distribution",
        "Autonomous Driving Platform",
        "Infotainment Solutions",
        "Smart Vehicle Architecture",
        "Software-Defined Vehicle Platform",
        "Vehicle Data Management",
        "Over-the-Air Software Updates",
      ],
    },
  ],
  spaceTech: [
    {
      symbol: "LMT",
      name: "Lockheed Martin",
      priceUSD: 460.01,
      openingPrice: 366.34,
      closingPrice: 460.2,
      highestPrice: "",
      lowestPrice: "",
      growth: "25.62%",
      marketCap: "116B",
      topProducts: [
        "F-35 Lightning II",
        "C-130J Super Hercules",
        "THAAD Missile Defense",
        "Aegis Combat System",
        "JASSM Missiles",
        "SBIRS Satellite System",
        "MH-60R Seahawk",
        "Trident II D5 Missile",
        "PAC-3 MSE",
        "Hypersonic Glide Vehicle (ARRW)",
      ],
    },
    {
      symbol: "NOC",
      name: "Northrop Grumman",
      priceUSD: 455.9,
      openingPrice: 308.87,
      closingPrice: 484,
      highestPrice: "",
      lowestPrice: "",
      growth: "56.70%",
      marketCap: "68B",
      topProducts: [
        "B-21 Raider",
        "RQ-4 Global Hawk",
        "E-2D Advanced Hawkeye",
        "Antares Rocket",
        "ICBM Modernization Systems",
        "James Webb Telescope Contribution",
        "Solid Rocket Motors",
        "Cybersecurity Solutions",
        "Advanced Battle Management System",
        "Space Launch Support Systems",
      ],
    },
    {
      symbol: "BA",
      name: "Boeing",
      priceUSD: 184.63,
      openingPrice: 185.88,
      closingPrice: 200.94,
      highestPrice: "",
      lowestPrice: "",
      growth: "8.10%",
      marketCap: "111B",
      topProducts: [
        "737 MAX",
        "787 Dreamliner",
        "777X",
        "F-15EX Eagle II",
        "Apache AH-64",
        "CH-47 Chinook",
        "P-8 Poseidon",
        "KC-46 Pegasus",
        "Starliner Spacecraft",
        "X-37B Spaceplane",
      ],
    },
    {
      symbol: "RTX",
      name: "Raytheon",
      priceUSD: 101.56,
      openingPrice: 120.08,
      closingPrice: 122.08,
      highestPrice: "",
      lowestPrice: "",
      growth: "1.67%",
      marketCap: "134B",
      topProducts: [
        "Patriot Missile System",
        "AMRAAM",
        "Tomahawk Cruise Missile",
        "NASAMS",
        "GhostEye Radar",
        "Stinger Missile",
        "Exoatmospheric Kill Vehicle",
        "Standard Missile-6 (SM-6)",
        "LTAMDS Radar",
        "Peregrine Missile",
      ],
    },
    {
      symbol: "RKLB",
      name: "Rocket Lab",
      priceUSD: 4.87,
      openingPrice: 9.75,
      closingPrice: 33.46,
      highestPrice: "",
      lowestPrice: "",
      growth: "243.18%",
      marketCap: "2B",
      topProducts: [
        "Electron Rocket",
        "Photon Satellite Bus",
        "Neutron Rocket (in development)",
        "Launch Complex 1",
        "Kick Stage",
        "Capstone Mission",
        "Hypersonic Suborbital Launch",
        "Spacecraft Components",
        "Autonomous Flight Termination System",
        "Mission Control Center (NZ)",
      ],
    },
    {
      symbol: "MAXR",
      name: "Maxar Technologies",
      priceUSD: 23,
      openingPrice: "",
      closingPrice: "",
      highestPrice: "",
      lowestPrice: "",
      growth: "",
      marketCap: "2B",
      topProducts: [
        "WorldView Satellites",
        "GeoEye-1",
        "Rapid Access Program",
        "3D Earth Intelligence",
        "Robotics for NASA Mars Missions",
        "Pleiades Neo Integration",
        "Integrated Mission Operations",
        "Synthetic Aperture Radar (SAR)",
        "Spacecraft Buses",
        "Deep Space Exploration Systems",
      ],
    },
    {
      symbol: "IRDM",
      name: "Iridium",
      priceUSD: 32.6,
      openingPrice: 25.42,
      closingPrice: 28.93,
      highestPrice: "",
      lowestPrice: "",
      growth: "13.81%",
      marketCap: "4B",
      topProducts: [
        "Iridium Certus",
        "Iridium NEXT Satellite Constellation",
        "Iridium GO!",
        "Satellite Messaging Services",
        "Push-to-Talk Radios",
        "Iridium Edge",
        "Aviation Connectivity",
        "Maritime Terminals",
        "Global Data Services",
        "IoT M2M Services",
      ],
    },
    {
      symbol: "SPCE",
      name: "Virgin Galactic",
      priceUSD: 1.17,
      openingPrice: 334,
      closingPrice: 2.94,
      highestPrice: "",
      lowestPrice: "",
      growth: "-99.12%",
      marketCap: "0.4B",
      topProducts: [
        "VSS Unity",
        "VMS Eve (Mothership)",
        "Commercial Space Tourism",
        "Astronaut Training Programs",
        "Gateway to Space (Spaceport America)",
        "Reusable Spaceplanes",
        "Next-gen Delta Class Spaceship",
        "Astronaut Merchandise",
        "Microgravity Research Missions",
        "High-Altitude Test Flights",
      ],
    },
    {
      symbol: "ASTR",
      name: "Astra Space",
      priceUSD: 0.65,
      openingPrice: "",
      closingPrice: "",
      highestPrice: "",
      lowestPrice: "",
      growth: "",
      marketCap: "0.2B",
      topProducts: [
        "Rocket 3 Series",
        "Rocket 4 Development",
        "Scalable Launch Operations",
        "Portable Launch System",
        "Astra Spacecraft Engine",
        "Modular Rocket Platforms",
        "In-house Propulsion Systems",
        "Flexible Launch Scheduling",
        "Dedicated Payload Deployment",
        "Orbital Transport Services",
      ],
    },
    {
      symbol: "RDW",
      name: "Redwire",
      priceUSD: 4.85,
      openingPrice: 10.7,
      closingPrice: 16.53,
      highestPrice: "",
      lowestPrice: "",
      growth: "54.49%",
      marketCap: "0.3B",
      topProducts: [
        "ISS Additive Manufacturing Facility (3D Printer)",
        "Roll-Out Solar Arrays",
        "Payload Handling Systems",
        "Advanced Sensors",
        "Microgravity R&D",
        "Lunar Terrain Vehicle Components",
        "Deployable Structures",
        "Spacecraft Avionics",
        "In-space Robotics",
        "Digital Engineering Solutions",
      ],
    },
  ],
  ai: [
    {
      symbol: "NVDA",
      name: "Nvidia",
      priceUSD: 130.98,
      openingPrice: 9.52,
      closingPrice: 147.9,
      highestPrice: "",
      lowestPrice: "",
      growth: "1453.57%",
      marketCap: "3.2T",
      topProducts: [
        "GeForce GPUs",
        "RTX AI GPUs",
        "CUDA",
        "TensorRT",
        "Omniverse",
        "NVIDIA DGX Systems",
        "Jetson AI Edge Devices",
        "NVIDIA Drive",
        "AI Enterprise Suite",
        "H100 Hopper GPU",
      ],
    },
    {
      symbol: "GOOGL",
      name: "Alphabet",
      priceUSD: 178.49,
      openingPrice: 70.96,
      closingPrice: 166.77,
      highestPrice: "",
      lowestPrice: "",
      growth: "135.02%",
      marketCap: "2.2T",
      topProducts: [
        "Google Search",
        "Google Cloud AI",
        "YouTube",
        "Bard (Gemini AI)",
        "DeepMind",
        "Android OS",
        "Chrome",
        "Google Ads",
        "Vertex AI",
        "TensorFlow",
      ],
    },
    {
      symbol: "MSFT",
      name: "Microsoft",
      priceUSD: 443.56,
      openingPrice: 203.14,
      closingPrice: 490.11,
      highestPrice: "",
      lowestPrice: "",
      growth: "141.27%",
      marketCap: "3.6T",
      topProducts: [
        "Windows OS",
        "Azure AI",
        "GitHub Copilot",
        "Office 365",
        "Power Platform",
        "Visual Studio",
        "OpenAI Partnership",
        "Azure OpenAI Service",
        "LinkedIn",
        "Bing Chat Enterprise",
      ],
    },
    {
      symbol: "AMZN",
      name: "Amazon",
      priceUSD: 186.12,
      openingPrice: 137.9,
      closingPrice: 212.77,
      highestPrice: "",
      lowestPrice: "",
      growth: "54.29%",
      marketCap: "1.95T",
      topProducts: [
        "Amazon.com",
        "AWS Bedrock",
        "Amazon Alexa",
        "Kindle",
        "Amazon Go",
        "Project Kuiper (satellite internet)",
        "Amazon Prime",
        "Amazon SageMaker",
        "AWS Lambda",
        "Amazon Polly",
      ],
    },
    {
      symbol: "META",
      name: "Meta Platforms",
      priceUSD: 493.78,
      openingPrice: 228.5,
      closingPrice: 712.2,
      highestPrice: "",
      lowestPrice: "",
      growth: "211.68%",
      marketCap: "1.3T",
      topProducts: [
        "Facebook",
        "Instagram",
        "WhatsApp",
        "Meta Ads Manager",
        "LLaMA Models",
        "Quest VR Headsets",
        "Meta Horizon Worlds",
        "Threads",
        "Meta AI Assistant",
        "Ray-Ban Meta Glasses",
      ],
    },
    {
      symbol: "IBM",
      name: "IBM",
      priceUSD: 170.14,
      openingPrice: 114.98,
      closingPrice: 293.79,
      highestPrice: "",
      lowestPrice: "",
      growth: "155.51%",
      marketCap: "155B",
      topProducts: [
        "Watsonx",
        "IBM Cloud Pak for Data",
        "Mainframes (zSeries)",
        "IBM Consulting AI",
        "AI Governance Tools",
        "Red Hat OpenShift",
        "IBM Power Systems",
        "Quantum Computing Services",
        "AIOps",
        "IBM Cloud Object Storage",
      ],
    },
    {
      symbol: "PLTR",
      name: "Palantir",
      priceUSD: 23.22,
      openingPrice: 10,
      closingPrice: 143.23,
      highestPrice: "",
      lowestPrice: "",
      growth: "1332.30%",
      marketCap: "51B",
      topProducts: [
        "Palantir Foundry",
        "Palantir Gotham",
        "Apollo for AI",
        "AI-Powered LLM Ops",
        "Edge AI Deployment",
        "MetaConstellation",
        "OpenAI Integration for Gov",
        "Palantir AIP",
        "Digital Twin Simulations",
        "Operational Intelligence Platforms",
      ],
    },
    {
      symbol: "AI",
      name: "C3.ai",
      priceUSD: 28.67,
      openingPrice: 100,
      closingPrice: 24.17,
      highestPrice: "",
      lowestPrice: "",
      growth: "-75.83%",
      marketCap: "3.4B",
      topProducts: [
        "C3 AI Platform",
        "C3 Generative AI Suite",
        "C3 AI CRM",
        "AI for Energy",
        "AI for Financial Services",
        "AI for Supply Chain",
        "AI for Healthcare",
        "Predictive Maintenance AI",
        "C3 AI Smart Grid",
        "C3 AI Ex Machina",
      ],
    },
    {
      symbol: "SOUN",
      name: "SoundHound AI",
      priceUSD: 5.47,
      openingPrice: 8.72,
      closingPrice: 9.82,
      highestPrice: "",
      lowestPrice: "",
      growth: "12.61%",
      marketCap: "1.5B",
      topProducts: [
        "SoundHound Voice AI",
        "Houndify",
        "Dynamic Interaction AI",
        "Multilingual Voice AI",
        "Smart Vehicle Assistants",
        "SoundHound Chat AI",
        "Edge AI for IoT",
        "Conversational Commerce",
        "AI for Hospitality",
        "Speech-to-Meaning Engine",
      ],
    },
    {
      symbol: "BBAI",
      name: "BigBear.ai",
      priceUSD: 1.24,
      openingPrice: 10,
      closingPrice: 5.23,
      highestPrice: "",
      lowestPrice: "",
      growth: "-47.70%",
      marketCap: "0.4B",
      topProducts: [
        "Observe (Data Ingestion)",
        "Prophesy Predictive AI",
        "Decision Dominance Platform",
        "Autonomous Systems AI",
        "Cyber AI Tools",
        "Global Supply Chain Analytics",
        "Predictive Intelligence Engine",
        "AI-powered ISR Systems",
        "Computer Vision for Defense",
        "AI Mission Planning Software",
      ],
    },
  ],
  banking: [
    {
      symbol: "JPM",
      name: "JPChaseMorgan",
      priceUSD: 197.53,
      openingPrice: 94.89,
      closingPrice: 281.26,
      highestPrice: "",
      lowestPrice: "",
      growth: "196.41%",
      marketCap: "570B",
      topProducts: [
        "Chase Credit Cards",
        "Commercial Banking Services",
        "Chase Mobile App",
        "Private Banking",
        "J.P. Morgan Asset Management",
        "Investment Banking",
        "Wealth Management",
        "Corporate & Investment Bank",
        "Auto Loans",
        "Business Banking Solutions",
      ],
    },
    {
      symbol: "BAC",
      name: "Bank of America",
      priceUSD: 40.07,
      openingPrice: 24.03,
      closingPrice: 46.66,
      highestPrice: "",
      lowestPrice: "",
      growth: "94.17%",
      marketCap: "320B",
      topProducts: [
        "BofA Mobile Banking App",
        "CashPro for Businesses",
        "Preferred Rewards Program",
        "Merrill Edge",
        "Auto Loans",
        "Business Advantage Banking",
        "Zelle Integration",
        "Small Business Services",
        "Wealth Management",
        "Credit Cards",
      ],
    },
    {
      symbol: "C",
      name: "Citigroup",
      priceUSD: 64.24,
      openingPrice: 51.76,
      closingPrice: 81.14,
      highestPrice: "",
      lowestPrice: "",
      growth: "56.76%",
      marketCap: "120B",
      topProducts: [
        "Citi Double Cash Card",
        "Citi Commercial Bank",
        "Citi Mobile App",
        "Private Banking",
        "Global Markets Division",
        "Retail Banking",
        "Citi ThankYou Rewards",
        "Citigold Wealth Management",
        "Institutional Clients Group",
        "Citi Flex Loan",
      ],
    },
    {
      symbol: "WFC",
      name: "Wells Fargo",
      priceUSD: 59.87,
      openingPrice: 25.73,
      closingPrice: 78.11,
      highestPrice: "",
      lowestPrice: "",
      growth: "203.58%",
      marketCap: "215B",
      topProducts: [
        "Wells Fargo Checking & Savings",
        "Zelle Payments",
        "Auto Loans",
        "Home Mortgage",
        "Credit Cards",
        "Mobile Banking App",
        "Business Loans",
        "Private Banking",
        "Commercial Real Estate Services",
        "Wealth and Investment Management",
      ],
    },
    {
      symbol: "GS",
      name: "Goldman Sachs",
      priceUSD: 452.78,
      openingPrice: 198.88,
      closingPrice: 662.11,
      highestPrice: "",
      lowestPrice: "",
      growth: "232.92%",
      marketCap: "153B",
      topProducts: [
        "Marcus by Goldman Sachs",
        "Ayco Financial Planning",
        "Investment Banking",
        "Private Wealth Management",
        "GS Select Credit Lines",
        "Asset Management",
        "Transaction Banking",
        "Institutional Client Services",
        "Consumer Banking",
        "Goldman Sachs Insights",
      ],
    },
    {
      symbol: "MS",
      name: "Morgan Stanley",
      priceUSD: 91.42,
      openingPrice: 48.41,
      closingPrice: 135.9,
      highestPrice: "",
      lowestPrice: "",
      growth: "180.73%",
      marketCap: "150B",
      topProducts: [
        "Morgan Stanley Wealth Management",
        "Global Capital Markets",
        "Investment Management",
        "Prime Brokerage Services",
        "Institutional Securities",
        "Financial Advisory Services",
        "E*TRADE Platform",
        "Equity Research",
        "Portfolio Management",
        "Sustainable Investing Solutions",
      ],
    },
    {
      symbol: "USB",
      name: "US Bancorp",
      priceUSD: 41.16,
      openingPrice: 30893,
      closingPrice: 26062,
      highestPrice: "",
      lowestPrice: "",
      growth: "-15.64%",
      marketCap: "64B",
      topProducts: [
        "U.S. Bank Mobile App",
        "Corporate Trust Services",
        "Retail Banking",
        "Business Checking Accounts",
        "Payment Services",
        "Mortgage Loans",
        "Wealth Management",
        "Credit Cards",
        "Personal Loans",
        "Digital Banking Tools",
      ],
    },
    {
      symbol: "PNC",
      name: "PNC Financial",
      priceUSD: 156.08,
      openingPrice: 105.77,
      closingPrice: 182.02,
      highestPrice: "",
      lowestPrice: "",
      growth: "72.09%",
      marketCap: "65B",
      topProducts: [
        "PNC Virtual Wallet",
        "Investment Services",
        "Business Banking Solutions",
        "Wealth Management",
        "Mortgage Products",
        "Corporate Banking",
        "Credit Cards",
        "Auto Loans",
        "PNC Mobile App",
        "Small Business Loans",
      ],
    },
    {
      symbol: "TFC",
      name: "Truist Financial",
      priceUSD: 39.19,
      openingPrice: 37.82,
      closingPrice: 41.45,
      highestPrice: "",
      lowestPrice: "",
      growth: "9.60%",
      marketCap: "52B",
      topProducts: [
        "Truist Online Banking",
        "Truist Commercial Banking",
        "Mortgage Services",
        "Personal Banking",
        "Credit Cards",
        "Small Business Checking",
        "Wealth & Retirement Planning",
        "Mobile Banking App",
        "Loan Services",
        "Insurance Solutions",
      ],
    },
    {
      symbol: "COF",
      name: "Capital One",
      priceUSD: 135.78,
      openingPrice: 62.85,
      closingPrice: 206.36,
      highestPrice: "",
      lowestPrice: "",
      growth: "228.34%",
      marketCap: "51B",
      topProducts: [
        "Capital One Credit Cards",
        "Capital One Cafés",
        "Auto Finance",
        "360 Performance Savings",
        "Mobile App",
        "Business Credit Cards",
        "Bank Accounts",
        "Capital One Shopping",
        "Commercial Banking",
        "Machine Learning Fraud Detection",
      ],
    },
  ],
  healthCare: [
    {
      symbol: "UNH",
      name: "UnitedHealth",
      priceUSD: 500.76,
      openingPrice: 295.83,
      closingPrice: 305.62,
      highestPrice: "",
      lowestPrice: "",
      growth: "3.31%",
      marketCap: "460B",
      topProducts: [
        "Optum Health Services",
        "Population Health Management",
        "UnitedHealthcare Insurance Plans",
        "Virtual Care Services",
        "Medicare Advantage",
        "Pharmacy Benefit Management (PBM)",
        "Employer Health Plans",
        "Behavioral Health Services",
        "Health Savings Accounts (HSA)",
        "Care Coordination Services",
      ],
    },
    {
      symbol: "PFE",
      name: "Pfizer",
      priceUSD: 28.74,
      openingPrice: 32.77,
      closingPrice: 24.31,
      highestPrice: "",
      lowestPrice: "",
      growth: "-25.82%",
      marketCap: "162B",
      topProducts: [
        "Comirnaty (COVID-19 vaccine)",
        "Oncology Pipeline Drugs",
        "Prevnar 13 (pneumococcal vaccine)",
        "Ibrance (breast cancer)",
        "Eliquis (blood thinner)",
        "Xeljanz (rheumatoid arthritis)",
        "Zithromax (antibiotic)",
        "Lipitor (cholesterol)",
        "Lyrica (nerve pain)",
        "Vyndaqel (ATTR-CM)",
      ],
    },
    {
      symbol: "JNJ",
      name: "Johnson & Johnson",
      priceUSD: 147.93,
      openingPrice: 140.69,
      closingPrice: 152.19,
      highestPrice: "",
      lowestPrice: "",
      growth: "8.17%",
      marketCap: "355B",
      topProducts: [
        "Stelara (autoimmune diseases)",
        "Janssen Pharmaceuticals (subsidiary portfolio)",
        "Tylenol",
        "Listerine",
        "Band-Aid",
        "Zyrtec",
        "Darzalex (multiple myeloma)",
        "Imbruvica (cancer)",
        "OneTouch Diabetes Products",
        "Neutrogena (skincare)",
      ],
    },
    {
      symbol: "MRNA",
      name: "Moderna",
      priceUSD: 117.91,
      openingPrice: 63,
      closingPrice: 26.8,
      highestPrice: "",
      lowestPrice: "",
      growth: "-57.46%",
      marketCap: "45B",
      topProducts: [
        "Spikevax (COVID-19 vaccine)",
        "mRNA Platform Services",
        "Flu mRNA Vaccine (in development)",
        "RSV mRNA Vaccine (in development)",
        "CMV mRNA Vaccine",
        "Zika mRNA Vaccine",
        "Cancer Vaccines (in trial)",
        "Rare Disease mRNA Programs",
        "Personalized Cancer Therapies",
        "Moderna Genomics Platform",
      ],
    },
    {
      symbol: "MRK",
      name: "Merck & Co.",
      priceUSD: 129.57,
      openingPrice: 73.88,
      closingPrice: 80.32,
      highestPrice: "",
      lowestPrice: "",
      growth: "8.72%",
      marketCap: "330B",
      topProducts: [
        "Keytruda (immunotherapy)",
        "Animal Health Products",
        "Gardasil (HPV vaccine)",
        "Januvia (diabetes)",
        "Lagevrio (COVID treatment)",
        "Isentress (HIV)",
        "Bravecto (pet care)",
        "Simponi (arthritis)",
        "ProQuad (MMRV vaccine)",
        "Cubicin (antibiotic)",
      ],
    },
    {
      symbol: "ABBV",
      name: "AbbVie",
      priceUSD: 168.45,
      openingPrice: 98.5,
      closingPrice: 185.55,
      highestPrice: "",
      lowestPrice: "",
      growth: "88.38%",
      marketCap: "300B",
      topProducts: [
        "Humira (autoimmune)",
        "Eye Care Portfolio (via Allergan)",
        "Skyrizi (psoriasis)",
        "Rinvoq (arthritis)",
        "Botox",
        "Ubrelvy (migraine)",
        "Vraylar (mental health)",
        "Imbruvica (cancer)",
        "Lupron (hormone therapy)",
        "Allergan Aesthetics",
      ],
    },
    {
      symbol: "BMY",
      name: "Bristol Myers",
      priceUSD: 41.73,
      openingPrice: 59.19,
      closingPrice: 47.03,
      highestPrice: "",
      lowestPrice: "",
      growth: "-20.54%",
      marketCap: "85B",
      topProducts: [
        "Opdivo (immunotherapy)",
        "Onureg (AML)",
        "Eliquis (blood thinner)",
        "Revlimid (cancer)",
        "Orencia (RA)",
        "Pomalyst (myeloma)",
        "Abecma (cell therapy)",
        "Zeposia (MS)",
        "Sprycel (leukemia)",
        "Empliciti (multiple myeloma)",
      ],
    },
    {
      symbol: "GILD",
      name: "Gilead Sciences",
      priceUSD: 64.22,
      openingPrice: 77.1,
      closingPrice: 107.2,
      highestPrice: "",
      lowestPrice: "",
      growth: "39.04%",
      marketCap: "80B",
      topProducts: [
        "Biktarvy (HIV)",
        "Cell Therapy (Kite Pharma)",
        "Descovy (HIV)",
        "Veklury (Remdesivir for COVID-19)",
        "Truvada (HIV)",
        "Atripla",
        "Sovaldi (HCV)",
        "Harvoni (HCV)",
        "Yescarta (CAR-T)",
        "Hepcludex",
      ],
    },
    {
      symbol: "LLY",
      name: "Eli Lilly",
      priceUSD: 898.88,
      openingPrice: 164.32,
      closingPrice: 778.08,
      highestPrice: "",
      lowestPrice: "",
      growth: "373.52%",
      marketCap: "850B",
      topProducts: [
        "Mounjaro (type 2 diabetes/obesity)",
        "Alzheimer’s Drug Donanemab (pipeline)",
        "Zyprexa (mental health)",
        "Trulicity (diabetes)",
        "Cymbalta (depression)",
        "Humalog (insulin)",
        "Olumiant (autoimmune)",
        "Basaglar (insulin)",
        "Emgality (migraine)",
        "Taltz (psoriasis)",
      ],
    },
    {
      symbol: "CVS",
      name: "CVS Health",
      priceUSD: 59.34,
      openingPrice: 64.97,
      closingPrice: 67.58,
      highestPrice: "",
      lowestPrice: "",
      growth: "4.02%",
      marketCap: "74B",
      topProducts: [
        "CVS Pharmacy",
        "OTC Health Products",
        "MinuteClinic",
        "Caremark (PBM)",
        "HealthHUBs",
        "Specialty Pharmacy Services",
        "Aetna Health Insurance",
        "CVS Mobile App",
        "Prescription Delivery",
        "Wellness Products",
      ],
    },
  ],
  realestate: [
    {
      symbol: "AMT",
      name: "American Tower",
      priceUSD: 188.77,
      openingPrice: 259.32,
      closingPrice: 223.91,
      highestPrice: "",
      lowestPrice: "",
      growth: "-13.65%",
      marketCap: "88B",
      topProducts: [
        "Cell Towers (US)",
        "Colocation Services",
        "Rooftop Antenna Infrastructure",
        "Edge Data Centers",
        "Fiber Solutions",
        "Small Cell Networks",
        "In-Building Wireless",
        "Smart City Infrastructure",
        "Global Tower Leasing",
        "Broadcast Infrastructure",
      ],
    },
    {
      symbol: "PLD",
      name: "Prologis",
      priceUSD: 113.65,
      openingPrice: 93.52,
      closingPrice: 108.13,
      highestPrice: "",
      lowestPrice: "",
      growth: "15.62%",
      marketCap: "105B",
      topProducts: [
        "Logistics Warehouses",
        "Global Logistics Parks",
        "Build-to-Suit Industrial Facilities",
        "E-commerce Fulfillment Centers",
        "Urban Distribution Hubs",
        "Sustainable Warehousing",
        "Cold Storage Warehouses",
        "Last-Mile Delivery Facilities",
        "High-Bay Distribution Centers",
        "Cross-Dock Facilities",
      ],
    },
    {
      symbol: "CCI",
      name: "Crown Castle",
      priceUSD: 99.28,
      openingPrice: 167.93,
      closingPrice: 103.19,
      highestPrice: "",
      lowestPrice: "",
      growth: "-38.55%",
      marketCap: "43B",
      topProducts: [
        "Wireless Towers",
        "Smart City Solutions",
        "Fiber Network Infrastructure",
        "Small Cell Deployments",
        "5G Network Support",
        "Indoor DAS (Distributed Antenna Systems)",
        "Public Safety Communications",
        "Backhaul Solutions",
        "Urban Wireless Nodes",
        "Private Network Hosting",
      ],
    },
    {
      symbol: "EQIX",
      name: "Equinix",
      priceUSD: 802.3,
      openingPrice: 703.04,
      closingPrice: 906.5,
      highestPrice: "",
      lowestPrice: "",
      growth: "28.94%",
      marketCap: "75B",
      topProducts: [
        "International Business Exchange (IBX) Data Centers",
        "Global Data Center Leasing",
        "Colocation Services",
        "Interconnection Hubs",
        "Equinix Fabric (Cloud Exchange)",
        "Edge Services",
        "Digital Infrastructure Services",
        "Hybrid Cloud Connectivity",
        "Bare Metal Services",
        "Data Center-as-a-Service",
      ],
    },
    {
      symbol: "PSA",
      name: "Public Storage",
      priceUSD: 292.35,
      openingPrice: 191.67,
      closingPrice: 295.6,
      highestPrice: "",
      lowestPrice: "",
      growth: "54.22%",
      marketCap: "52B",
      topProducts: [
        "Self-Storage Units",
        "Large Vehicle Storage",
        "Climate-Controlled Units",
        "Business Storage Solutions",
        "Drive-Up Access Units",
        "Personal Storage Lockers",
        "Online Storage Auctions",
        "24/7 Access Units",
        "RV and Boat Storage",
        "Storage Insurance Services",
      ],
    },
    {
      symbol: "SPG",
      name: "Simon Property",
      priceUSD: 144.16,
      openingPrice: 69.8,
      closingPrice: 160.12,
      highestPrice: "",
      lowestPrice: "",
      growth: "129.40%",
      marketCap: "47B",
      topProducts: [
        "Premium Outlet Malls",
        "Simon Giftcards",
        "Luxury Retail Leasing",
        "Entertainment Anchors",
        "Mixed-Use Development",
        "Mall Redevelopment Projects",
        "Experiential Retail Spaces",
        "Food Court Management",
        "E-commerce Fulfillment Integration",
        "Retail Tenant Services",
      ],
    },
    {
      symbol: "WELL",
      name: "Welltower",
      priceUSD: 99.89,
      openingPrice: 52.19,
      closingPrice: 154.25,
      highestPrice: "",
      lowestPrice: "",
      growth: "195.55%",
      marketCap: "52B",
      topProducts: [
        "Senior Housing (Triple-Net)",
        "International Healthcare Properties",
        "Assisted Living Facilities",
        "Memory Care Units",
        "Post-Acute Care Centers",
        "Hospice Real Estate",
        "Wellness Communities",
        "Healthcare Real Estate Partnerships",
        "Outpatient Medical Buildings",
        "Behavioral Health Facilities",
      ],
    },
    {
      symbol: "O",
      name: "Realty Income",
      priceUSD: 54.12,
      openingPrice: 57.9,
      closingPrice: 57.98,
      highestPrice: "",
      lowestPrice: "",
      growth: "0.14%",
      marketCap: "46B",
      topProducts: [
        "Single-Tenant Commercial Properties",
        "Investment-Grade Tenants",
        "Retail Real Estate Leasing",
        "Monthly Dividend Real Estate",
        "Net-Lease Assets",
        "Industrial Net-Leased Real Estate",
        "Long-Term Retail Tenancy",
        "Experiential Retail Properties",
        "U.S. and International Expansion",
        "Diversified Real Estate Portfolio",
      ],
    },
    {
      symbol: "AVB",
      name: "AvalonBay",
      priceUSD: 196.47,
      openingPrice: 155.03,
      closingPrice: 206.13,
      highestPrice: "",
      lowestPrice: "",
      growth: "32.96%",
      marketCap: "28B",
      topProducts: [
        "Luxury Apartment Communities",
        "Sustainable Living Initiatives",
        "Mixed-Use Residential Properties",
        "Urban Infill Apartments",
        "Transit-Oriented Developments",
        "Smart Home Apartment Features",
        "Resident Amenity Programs",
        "Flexible Leasing Options",
        "Suburban Apartment Complexes",
        "Market-Rate Housing Units",
      ],
    },
    {
      symbol: "DLR",
      name: "Digital Realty",
      priceUSD: 140.05,
      openingPrice: 142.77,
      closingPrice: 177.66,
      highestPrice: "",
      lowestPrice: "",
      growth: "24.44%",
      marketCap: "43B",
      topProducts: [
        "Carrier-Neutral Data Centers",
        "Sustainable Data Center Solutions",
        "Interconnection Platforms",
        "Digital Exchange Services",
        "Cloud Infrastructure Hosting",
        "Hyperscale Data Center Services",
        "Colocation and Hybrid Solutions",
        "Data Center Analytics",
        "Enterprise IT Infrastructure",
        "Edge Computing Support",
      ],
    },
  ],
  energy: [
    {
      symbol: "XOM",
      name: "ExxonMobil",
      priceUSD: 112.57,
      openingPrice: 44.49,
      closingPrice: 108.34,
      highestPrice: "",
      lowestPrice: "",
      growth: "143.52%",
      marketCap: "455B",
      topProducts: [
        "Crude oil",
        "Carbon capture & storage solutions",
        "Natural gas production",
        "Petrochemicals",
        "Lubricants (Mobil)",
        "LNG (Liquefied Natural Gas)",
        "Low-carbon hydrogen",
        "Biofuels",
        "Refining & marketing",
        "Upstream exploration",
      ],
    },
    {
      symbol: "CVX",
      name: "Chevron",
      priceUSD: 154.11,
      openingPrice: 89.28,
      closingPrice: 143.55,
      highestPrice: "",
      lowestPrice: "",
      growth: "60.79%",
      marketCap: "290B",
      topProducts: [
        "Crude oil",
        "Carbon capture & low-carbon technologies",
        "Natural gas",
        "Renewable diesel",
        "LNG shipping",
        "Petrochemical manufacturing",
        "Refining operations",
        "Base oils & additives",
        "Lubricants",
        "Deepwater drilling",
      ],
    },
    {
      symbol: "COP",
      name: "ConocoPhillips",
      priceUSD: 112.65,
      openingPrice: 42.35,
      closingPrice: 89.39,
      highestPrice: "",
      lowestPrice: "",
      growth: "111.07%",
      marketCap: "135B",
      topProducts: [
        "Crude oil",
        "International upstream projects",
        "Natural gas liquids",
        "Tight oil development",
        "Arctic oil projects",
        "Shale production",
        "Global LNG supply",
        "Sustainable operations",
        "Carbon solutions",
        "Heavy oil production",
      ],
    },
    {
      symbol: "SLB",
      name: "Schlumberger",
      priceUSD: 47.15,
      openingPrice: 18.5,
      closingPrice: 33.5,
      highestPrice: "",
      lowestPrice: "",
      growth: "81.08%",
      marketCap: "67B",
      topProducts: [
        "Drilling services",
        "Subsea systems",
        "Well construction",
        "Reservoir evaluation",
        "Geophysical services",
        "Production systems",
        "Digital oilfield solutions",
        "AI in energy",
        "Energy transition technologies",
        "Wireline services",
      ],
    },
    {
      symbol: "EOG",
      name: "EOG Resources",
      priceUSD: 121.55,
      openingPrice: 51.03,
      closingPrice: 120.68,
      highestPrice: "",
      lowestPrice: "",
      growth: "136.49%",
      marketCap: "70B",
      topProducts: [
        "Crude oil",
        "Mineral & royalty interests",
        "Natural gas production",
        "Horizontal drilling",
        "Premium well targets",
        "Fracking operations",
        "Low-cost energy operations",
        "Environmental stewardship",
        "Smart pad drilling",
        "Multi-well development",
      ],
    },
    {
      symbol: "OXY",
      name: "Occidental Petroleum",
      priceUSD: 63.71,
      openingPrice: 18.32,
      closingPrice: 42.48,
      highestPrice: "",
      lowestPrice: "",
      growth: "131.88%",
      marketCap: "56B",
      topProducts: [
        "Crude oil",
        "Environmental services",
        "Carbon management",
        "Low-carbon ventures",
        "Enhanced oil recovery (EOR)",
        "CO2 sequestration",
        "Midstream services",
        "Basic chemicals",
        "OxyChem PVC products",
        "Water recycling systems",
      ],
    },
    {
      symbol: "BKR",
      name: "Baker Hughes",
      priceUSD: 33.41,
      openingPrice: 15.6,
      closingPrice: 37.97,
      highestPrice: "",
      lowestPrice: "",
      growth: "143.40%",
      marketCap: "34B",
      topProducts: [
        "Oilfield services",
        "Industrial services",
        "Energy technology solutions",
        "Compressor systems",
        "Turbomachinery",
        "Digital twins (for oil)",
        "Subsea production systems",
        "Carbon capture systems",
        "Hydrogen technology",
        "Artificial lift systems",
      ],
    },
    {
      symbol: "MRO",
      name: "Marathon Oil",
      priceUSD: 27.55,
      openingPrice: "",
      closingPrice: "",
      highestPrice: "",
      lowestPrice: "",
      growth: "#DIV/0!",
      marketCap: "16B",
      topProducts: [
        "Crude oil",
        "ESG-integrated operations",
        "Shale oil production",
        "Marcellus & Eagle Ford assets",
        "Resource-rich basins",
        "Natural gas production",
        "Condensate extraction",
        "Hydraulic fracturing services",
        "Upstream portfolio diversification",
        "Corporate emissions strategy",
      ],
    },
    {
      symbol: "DVN",
      name: "Devon Energy",
      priceUSD: 46.38,
      openingPrice: 11.36,
      closingPrice: 32.35,
      highestPrice: "",
      lowestPrice: "",
      growth: "184.77%",
      marketCap: "30B",
      topProducts: [
        "Crude oil",
        "Royalty & mineral interest management",
        "Shale assets (Delaware Basin)",
        "Stack formation operations",
        "Drilling innovations",
        "Sustainable energy management",
        "Natural gas liquids (NGL)",
        "Pad development programs",
        "Carbon-conscious strategies",
        "Advanced analytics in drilling",
      ],
    },
    {
      symbol: "VLO",
      name: "Valero Energy",
      priceUSD: 148.28,
      openingPrice: 59.2,
      closingPrice: 135.85,
      highestPrice: "",
      lowestPrice: "",
      growth: "129.48%",
      marketCap: "50B",
      topProducts: [
        "Gasoline",
        "Renewable energy investments",
        "Diesel fuels",
        "Jet fuel",
        "Biofuel production",
        "Refining operations",
        "Asphalt & petrochemicals",
        "Renewable diesel",
        "Ethanol production",
        "Logistics & pipelines",
      ],
    },
  ],
  consumerElectronics: [
    {
      symbol: "AAPL",
      name: "Apple Inc.",
      openingPrice: 91.28,
      closingPrice: 200.3,
      highestPrice: "",
      lowestPrice: "",
      growth: "119.43%",
      marketCap: "3.28T",
      topProducts: [
        "iPhone",
        "Apple Pay",
        "MacBook",
        "iPad",
        "Apple Watch",
        "AirPods",
        "iOS",
        "App Store",
        "Apple TV+",
        "iCloud",
      ],
    },
    {
      symbol: "MSFT",
      name: "Microsoft Corp.",
      openingPrice: 203.14,
      closingPrice: 490.11,
      highestPrice: "",
      lowestPrice: "",
      growth: "141.27%",
      marketCap: "2.79T",
      topProducts: [
        "Windows OS",
        "GitHub",
        "Microsoft Office",
        "Azure Cloud",
        "Xbox",
        "Teams",
        "LinkedIn",
        "Visual Studio",
        "Bing AI",
        "Copilot",
      ],
    },
    {
      symbol: "GOOGL",
      name: "Alphabet Inc.",
      openingPrice: 70.56,
      closingPrice: 167.74,
      highestPrice: "",
      lowestPrice: "",
      growth: "137.73%",
      marketCap: "1.87T",
      topProducts: [
        "Google Search",
        "Waymo",
        "YouTube",
        "Android",
        "Google Cloud",
        "Gmail",
        "Google Maps",
        "Google Ads",
        "Bard (Gemini)",
        "Chrome OS",
      ],
    },
    {
      symbol: "NVDA",
      name: "Nvidia Corp.",
      openingPrice: 9.52,
      closingPrice: 147.9,
      highestPrice: "",
      lowestPrice: "",
      growth: "1453.57%",
      marketCap: "3.51T",
      topProducts: [
        "GeForce GPUs",
        "Nvidia DRIVE",
        "TensorRT",
        "CUDA",
        "DGX Systems",
        "Omniverse",
        "AI Enterprise Suite",
        "Jetson",
        "RTX Graphics Cards",
        "Hopper Architecture",
      ],
    },
    {
      symbol: "AMD",
      name: "Advanced Micro Devices",
      openingPrice: 52.63,
      closingPrice: 138.43,
      highestPrice: "",
      lowestPrice: "",
      growth: "163.02%",
      marketCap: "206B",
      topProducts: [
        "Ryzen Processors",
        "Embedded Solutions",
        "EPYC Server Chips",
        "Radeon Graphics Cards",
        "Threadripper",
        "Xilinx FPGA (acquisition)",
        "Instinct AI Accelerators",
        "FreeSync",
        "Versal AI Engines",
        "Adrenalin Software",
      ],
    },
    {
      symbol: "CSCO",
      name: "Cisco Systems",
      openingPrice: 46.54,
      closingPrice: 67.89,
      highestPrice: "",
      lowestPrice: "",
      growth: "45.87%",
      marketCap: "259B",
      topProducts: [
        "Catalyst Switches",
        "TelePresence",
        "Meraki",
        "Cisco Webex",
        "SecureX",
        "Cisco Routers",
        "AppDynamics",
        "Cisco DNA Center",
        "ThousandEyes",
        "Umbrella Security",
      ],
    },
    {
      symbol: "APH",
      name: "Amphenol Corp.",
      openingPrice: 24.04,
      closingPrice: 95.8,
      highestPrice: "",
      lowestPrice: "",
      growth: "298.50%",
      marketCap: "112B",
      topProducts: [
        "RF Connectors",
        "Military & Marine Solutions",
        "Fiber Optic Products",
        "Coaxial Connectors",
        "Cable Assemblies",
        "Sensor Solutions",
        "Backplane Systems",
        "Aerospace Electronics",
        "Industrial Power Connectors",
        "High-Speed Interconnects",
      ],
    },
    {
      symbol: "ANET",
      name: "Arista Networks",
      openingPrice: 13.16,
      closingPrice: 94.97,
      highestPrice: "",
      lowestPrice: "",
      growth: "621.66%",
      marketCap: "113B",
      topProducts: [
        "Arista 7000 Series Switches",
        "Zero Trust Security",
        "CloudVision",
        "EOS (Extensible Operating System)",
        "Data Center Fabrics",
        "Cognitive Campus",
        "AI Networking",
        "Arista AVA",
        "Cloud Networking Platforms",
        "Next-gen Routing",
      ],
    },
    {
      symbol: "DELL",
      name: "Dell Technologies",
      openingPrice: 27.91,
      closingPrice: 120.59,
      highestPrice: "",
      lowestPrice: "",
      growth: "332.07%",
      marketCap: "79B",
      topProducts: [
        "XPS Laptops",
        "Dell Unified Workspace",
        "Alienware",
        "Dell EMC Storage",
        "PowerEdge Servers",
        "Latitude Laptops",
        "VMware (spinoff tech)",
        "Precision Workstations",
        "Dell CloudIQ",
        "Display Monitors",
      ],
    },
    {
      symbol: "CDNS",
      name: "Cadence Design Systems",
      openingPrice: 95.7,
      closingPrice: 296.8,
      highestPrice: "",
      lowestPrice: "",
      growth: "210.14%",
      marketCap: "82B",
      topProducts: [
        "Virtuoso Platform",
        "AI-Driven Design Intelligence",
        "Spectre Simulation Tools",
        "Innovus Implementation System",
        "Tensilica DSPs",
        "Clarity 3D Solver",
        "Celsius Thermal Solver",
        "JasperGold Formal Verification",
        "Xcelium Parallel Simulator",
        "Custom Compiler Suite",
      ],
    },
  ],
  "airline&logistics": [
    {
      symbol: "UPS",
      name: "United Parcel Service",
      openingPrice: 117.86,
      closingPrice: 100.62,
      highestPrice: "",
      lowestPrice: "",
      growth: "-14.63%",
      marketCap: "85.5B",
      topProducts: [
        "UPS Ground",
        "UPS Capital Services",
        "UPS Air Freight",
        "UPS Supply Chain Solutions",
        "UPS Worldwide Express",
        "UPS SurePost",
        "My Choice for Business",
        "UPS Access Point",
        "Returns Manager",
        "Billing Center",
      ],
    },
    {
      symbol: "FDX",
      name: "FedEx Corporation",
      openingPrice: 256.15,
      closingPrice: 229.51,
      highestPrice: "",
      lowestPrice: "",
      growth: "-10.40%",
      marketCap: "65B",
      topProducts: [
        "FedEx Express",
        "FedEx Dataworks",
        "FedEx Ground",
        "FedEx Freight",
        "FedEx Office",
        "FedEx SameDay",
        "FedEx Ship Manager",
        "FedEx Trade Networks",
        "FedEx Supply Chain",
        "FedEx Delivery Manager",
      ],
    },
    {
      symbol: "ODFL",
      name: "Old Dominion Freight Line",
      openingPrice: 85.5,
      closingPrice: 161.97,
      highestPrice: "",
      lowestPrice: "",
      growth: "89.44%",
      marketCap: "44B",
      topProducts: [
        "OD Domestic",
        "OD Customer Tools (Track Rate.)",
        "OD Global",
        "OD Expedited",
        "OD Technology Solutions",
        "Freight Tracking Tools",
        "OD Terminal Services",
        "Freight Claims Assistance",
        "Supply Chain Consulting",
        "OD Web Tools",
      ],
    },
    {
      symbol: "DAL",
      name: "Delta Air Lines",
      openingPrice: 29.02,
      closingPrice: 46.56,
      highestPrice: "",
      lowestPrice: "",
      growth: "60.44%",
      marketCap: "30.9B",
      topProducts: [
        "Delta One",
        "Delta Wi-Fi & In-flight Entertainment",
        "Main Cabin",
        "Delta Premium Select",
        "Delta Comfort+",
        "SkyMiles Loyalty Program",
        "Delta Sky Club",
        "Delta Cargo",
        "Delta Vacations",
        "Fly Delta App",
      ],
    },
    {
      symbol: "UAL",
      name: "United Airlines Holdings",
      openingPrice: 36.92,
      closingPrice: 79.02,
      highestPrice: "",
      lowestPrice: "",
      growth: "114.03%",
      marketCap: "32B",
      topProducts: [
        "United Polaris (Business Class)",
        "Eco-Skies (Sustainable Travel)",
        "United First",
        "United Basic Economy",
        "MileagePlus",
        "United Club",
        "United Cargo",
        "United CleanPlus",
        "United Private Screening",
        "Wi-Fi on Board",
      ],
    },
    {
      symbol: "LUV",
      name: "Southwest Airlines",
      openingPrice: 35.29,
      closingPrice: 31.86,
      highestPrice: "",
      lowestPrice: "",
      growth: "-9.72%",
      marketCap: "27B",
      topProducts: [
        "Wanna Get Away Fares",
        "Group Travel Services",
        "EarlyBird Check-In",
        "Rapid Rewards",
        "Business Select",
        "Southwest Cargo",
        "Companion Pass",
        "No Change Fees",
        "In-flight Messaging",
        "Southwest Vacations",
      ],
    },
    {
      symbol: "EXPD",
      name: "Expeditors International",
      openingPrice: 76.7,
      closingPrice: 114.16,
      highestPrice: "",
      lowestPrice: "",
      growth: "48.84%",
      marketCap: "25B",
      topProducts: [
        "Air Freight",
        "Consulting Services",
        "Ocean Freight",
        "Customs Brokerage",
        "Transcon Services",
        "Trade Compliance",
        "Warehousing",
        "Risk Management",
        "Expeditors Order Management",
        "Transportation Management",
      ],
    },
    {
      symbol: "JBLU",
      name: "JetBlue Airways",
      openingPrice: 11.32,
      closingPrice: 4.27,
      highestPrice: "",
      lowestPrice: "",
      growth: "-62.28%",
      marketCap: "3.5B",
      topProducts: [
        "Mint (Premium Class)",
        "JetBlue Travel Products",
        "Blue Basic",
        "Even More Space",
        "TrueBlue Rewards",
        "Fly-Fi (In-Flight Wi-Fi)",
        "JetBlue Vacations",
        "JetBlue Card",
        "Carbon Offset Program",
        "Seatback Entertainment",
      ],
    },
    {
      symbol: "ALK",
      name: "Alaska Air Group",
      openingPrice: 37.18,
      closingPrice: 49.56,
      highestPrice: "",
      lowestPrice: "",
      growth: "33.30%",
      marketCap: "5.66B",
      topProducts: [
        "First Class",
        "In-flight Entertainment & Wi-Fi",
        "Main Cabin",
        "Alaska Lounge",
        "Mileage Plan",
        "Premium Class",
        "Alaska Vacations",
        "Club 49 (Alaska Residents)",
        "Mobile Check-in",
        "Sustainable Aviation Fuel Program",
      ],
    },
    {
      symbol: "AAL",
      name: "American Airlines Group",
      openingPrice: 13.48,
      closingPrice: 11.37,
      highestPrice: "",
      lowestPrice: "",
      growth: "-15.65%",
      marketCap: "32B",
      topProducts: [
        "Flagship First",
        "In-flight Wi-Fi & Entertainment",
        "Main Cabin Extra",
        "AAdvantage Program",
        "American Airlines Vacations",
        "Flagship Business",
        "Admirals Club",
        "Premium Economy",
        "Cargo Services",
        "AA Mobile App",
      ],
    },
  ],
  "media&entertainement": [
    {
      symbol: "NFLX",
      name: "Netflix Inc.",
      openingPrice: 454,
      closingPrice: 1279.11,
      highestPrice: "",
      lowestPrice: "",
      growth: "181.74%",
      marketCap: "519B",
      topProducts: [
        "Netflix Streaming Platform",
        "The Crown",
        "Stranger Things",
        "Netflix Originals",
        "Money Heist",
        "Squid Game",
        "Wednesday",
        "You",
        "Narcos",
        "The Witcher",
      ],
    },
    {
      symbol: "DIS",
      name: "Walt Disney Co.",
      openingPrice: 112.82,
      closingPrice: 118.65,
      highestPrice: "",
      lowestPrice: "",
      growth: "5.17%",
      marketCap: "212B",
      topProducts: [
        "Disney+",
        "20th Century Studios",
        "Disney Parks",
        "Marvel Studios",
        "Lucasfilm",
        "ESPN",
        "Hulu",
        "Pixar",
        "National Geographic",
        "ABC Network",
      ],
    },
    {
      symbol: "CMCSA",
      name: "Comcast Corp.",
      openingPrice: 39.61,
      closingPrice: 35.21,
      highestPrice: "",
      lowestPrice: "",
      growth: "-11.11%",
      marketCap: "153B",
      topProducts: [
        "Xfinity Internet",
        "Universal Parks & Resorts",
        "NBCUniversal",
        "Peacock",
        "Xfinity Mobile",
        "Sky",
        "Comcast Business",
        "X1 Entertainment Platform",
        "Telemundo",
        "Fandango",
      ],
    },
    {
      symbol: "LYV",
      name: "Live Nation Entertainment",
      openingPrice: 44.86,
      closingPrice: 147.78,
      highestPrice: "",
      lowestPrice: "",
      growth: "229.42%",
      marketCap: "33.7B",
      topProducts: [
        "Ticketmaster",
        "EDC",
        "Live Nation Concerts",
        "Lollapalooza",
        "Live Nation Urban",
        "Festival Passport",
        "House of Blues",
        "Live Nation Sponsorships",
        "Rolling Loud",
        "VIP Nation",
      ],
    },
    {
      symbol: "WBD",
      name: "Warner Bros Discovery",
      openingPrice: 21.23,
      closingPrice: 10.9,
      highestPrice: "",
      lowestPrice: "",
      growth: "-48.66%",
      marketCap: "26.2B",
      topProducts: [
        "Max (formerly HBO Max)",
        "Eurosport",
        "Discovery+",
        "Warner Bros. Pictures",
        "CNN",
        "Cartoon Network",
        "TLC",
        "Food Network",
        "Animal Planet",
        "HBO Originals",
      ],
    },
    {
      symbol: "FWONA",
      name: "Formula One Group",
      openingPrice: 28.74,
      closingPrice: 94.82,
      highestPrice: "",
      lowestPrice: "",
      growth: "229.92%",
      marketCap: "24.5B",
      topProducts: [
        "Formula 1 World Championship",
        "Global Broadcasting Rights",
        "F1 TV Pro",
        "F1 Esports",
        "FIA Partnership",
        "F1 Fan Zone",
        "F1 Experiences",
        "F1 Mobile Racing",
        "F1 Hospitality",
        "F1 Data & Insights",
      ],
    },
    {
      symbol: "FOX",
      name: "Fox Corp.",
      openingPrice: 26.8,
      closingPrice: 51.31,
      highestPrice: "",
      lowestPrice: "",
      growth: "91.46%",
      marketCap: "24.3B",
      topProducts: [
        "Fox News",
        "Fox Local Stations",
        "Fox Sports",
        "Fox Entertainment",
        "Tubi",
        "Fox Nation",
        "Fox Weather",
        "Fox Business",
        "Fox Broadcasting Company",
        "Fox Bet",
      ],
    },
    {
      symbol: "PARA",
      name: "Paramount Global",
      openingPrice: 23.33,
      closingPrice: 12.21,
      highestPrice: "",
      lowestPrice: "",
      growth: "-47.66%",
      marketCap: "10B",
      topProducts: [
        "Paramount+",
        "CBS Sports",
        "Nickelodeon",
        "MTV",
        "BET",
        "Comedy Central",
        "Pluto TV",
        "Showtime",
        "Smithsonian Channel",
        "CBS News",
      ],
    },
    {
      symbol: "ATVI",
      name: "Activision Blizzard",
      openingPrice: "",
      closingPrice: "",
      highestPrice: "",
      lowestPrice: "",
      growth: "",
      marketCap: "60B",
      topProducts: [
        "Call of Duty",
        "Battle.net",
        "World of Warcraft",
        "Diablo",
        "Overwatch",
        "Candy Crush",
        "Hearthstone",
        "StarCraft",
        "Crash Bandicoot",
        "Tony Hawk’s Pro Skater",
      ],
    },
    {
      symbol: "MGM",
      name: "MGM Resorts",
      openingPrice: 16.95,
      closingPrice: 34.2,
      highestPrice: "",
      lowestPrice: "",
      growth: "101.77%",
      marketCap: "18B",
      topProducts: [
        "Bellagio",
        "MGM Sportsbook",
        "MGM Grand",
        "Aria Resort & Casino",
        "Mandalay Bay",
        "M life Rewards",
        "BetMGM",
        "Park MGM",
        "Luxor",
        "MGM Signature",
      ],
    },
  ],
};
