import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ClickTracker from "@/components/clickTracker/ClickTracker";
import { Suspense } from "react";
import { SmoothCursor } from "@/components/ui/smooth-cursor";
import HamburgerMenu from "@/components/hamburger/Hamburger";
import { useAppStore } from "@/store/useStore";
import ClientRoot from "@/components/clientRoot/ClientRoot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Graviti",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased select-none`}>
        <ClientRoot />

        <ClickTracker />
        {/* <SmoothCursor /> */}
        <Toaster
          position="top-center"
          toastOptions={{
            duration: 4000,
            style: {
              padding: "1rem 1.5rem",
              borderRadius: "16px",
              fontSize: "clamp(0.875rem, 2.5vw, 1rem)",
              fontWeight: 500,
              color: "#fff",
              backdropFilter: "blur(6px)",
              WebkitBackdropFilter: "blur(6px)",
              boxShadow: "0 8px 30px rgba(0,0,0,0.2)",
            },
            success: {
              style: {
                background: "linear-gradient(135deg, #00C9A7, #007B55)",
              },
              iconTheme: {
                primary: "#ffffff",
                secondary: "#00C9A7",
              },
            },
            error: {
              style: {
                background: "linear-gradient(135deg, #FF6B6B, #C9184A)",
              },
              iconTheme: {
                primary: "#ffffff",
                secondary: "#FF6B6B",
              },
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
